### PR TITLE
Add a generic format validator

### PR DESCRIPTION
**Pull request by lexun**
- will allow users easily create custom content validations
- should dry up other validations by providing a reusable base

### CODE REVIEW

**Comment by lexun** [comment]
@ryanstout  I'm aiming to come back to this and wrap it up on Friday. I'd like to do some integration tests to confirm that multiple error messages come back if there are multiple failed criteria on a validation, and if there are multiple failed validations on a field. Do you have an idea of where you'd like something like that to go?

**Comment by ryanstout** [comment]
@lexun I have the integration specs in spec/integration  I'll probably want to organize that folder at some point, but you can see some examples of the integration specs in there.  I'm just using capybara with rspec.  It boots up the "kitchen sink" app at spec/apps/kitchen_sink.  Feel free to add more stuff into that app.  See here for info on running the integration specs: http://docs.voltframework.com/en/docs/testing.html

**Comment by ryanstout** [comment]
@lexun Also, I'm around today on gitter if you need anything.

**Comment by lexun** [comment]
@ryanstout  Hey, there is still a good deal more that could be done here but I think it's in a good enough state to merge what we have so far, and do the rest in future PRs. Let me know what you think.

**Comment by ryanstout** [comment]
@lexun cool, thanks for working on this.  Merging in.

**Pull request merged**
