### PR TITLE
Drop mongo table

### PR DESCRIPTION
**Pull request by dennym**

### CODE REVIEW

**Comment by ryanstout** [comment]
cool, thanks for this.  I'll be working on volt this evening and will merge this in.

**Comment by dennym** [comment]
Cool thing... on next iteration this should be moved out into its own file to extend it easier with more option of database handling

**Comment by ryanstout** [comment]
Thanks for the PR, sorry it took me a while to merge.  If you get a chance, can you add details of this to the docs?  github.com/voltrb/docs

**Comment by dennym** [comment]
yeah sure I will do that the next few days :)

**Pull request merged**
