### PR TITLE
suppress the logging of plaintext passwords

### PR DESCRIPTION
**Pull request by rhgraysonii**
This is pretty simple. 

All I did was extract a `parse_args` private method that maps through the args, removes them if they are forbidden (defaulting to just forbidding password), and then compacts the array (the map returns nil in the removed spots, and an empty string looks weird/ugly with just a hanging comma when it prints), and joins it to a comma-separated string for the logger.

I have tested it locally and it seems to be working.

I have not been able to get the specs to run, individually or in bulk, so I did not write a test with it. If you would like to help me out w.r.t to getting the testing suite running I will gladly get one written.

### CODE REVIEW

**Comment by ryanstout** [comment]
@rhgraysonii would you mind adding specs for this?

**Comment by rhgraysonii** [comment]
@ryanstout I would love to but I'm having issues with my testing suite locally -- any ideas on how I could fix it? Guard keeps getting:

```

18:12:02 - INFO - Running: spec/extra_core/logger_spec.rb
/home/bobby/projects/volt/spec/extra_core/logger_spec.rb:2:in `<top (required)>': uninitialized constant Volt (NameError)
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/bin/rspec:23:in `load'
	from /home/bobby/projects/volt/vendor/bundle/ruby/2.1.0/bin/rspec:23:in `<main>'
```
Whenever I save a file, same thing happens when I try to run all specs. Based off the latest master branch, pulled ~30 minutes ago. Ubuntu 14.10

**Comment by ryanstout** [comment]
@rhgraysonii sorry, I would love to help, but I don't want to get sidetracked time wise.  Maybe keep working on it on your end for a while longer, then hit me up if you can't get it.

**Comment by rhgraysonii** [comment]
@ryanstout Sounds good, I'm consulting a friend who is a bit of a wizard when it comes to Rspec. Hopefully he sets me straight. Testing simple STDOUT printing isnt exactly difficult so I'm really just moreso annoyed I can't get it to run local. Will ping you once I have a working spec, or once things slow down on your end in the coming days if it really ends up being a humdinger for some reason.

**Comment by dfyx** [comment]
I'd really prefer replacing the attributes with `*******` instead of removing them entirely. Makes it clearer that they were in fact transmitted. I'm not 100% sure but I think that's what rails does. I'll look it up in a few minutes.

**Comment by rhgraysonii** [comment]
@dfyx @ryanstout is planning on adding customizable filters etc and is implementing it on his end. So i closed the PR on this one due to that

**Comment by ryanstout** [comment]
@dfyx yea, your right, doing *'s is better I think.  I'm reworking this right now actually.

**Comment by dfyx** [comment]
Alright, I looked it up. The current version of rails just replaces them with `[FILTERED]`.

Things to look at: [ParameterFilter](https://github.com/rails/rails/blob/390f09efa3850d735bb9426a4a41a81f8ea400d2/actionpack/lib/action_dispatch/http/parameter_filter.rb), [FilterParameters](https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/actionpack/lib/action_dispatch/http/filter_parameters.rb)

**Comment by ryanstout** [comment]
@dfyx think there's a security risk showing how long the password is?

**Comment by dfyx** [comment]
I'd say it is. Knowing the length basically reduces the time it takes to bruteforce the password by 50%.

**Comment by ryanstout** [comment]
@dfyx yea, I agree.  I'll do the same thing as rails then.

**Pull request closed without merging**
