### PR TITLE
A replacement for .sync on the client side

### PR DESCRIPTION
**Pull request by pencilcheck**
Now a promise can chain methods as well.
A promise can be chained with methods supported by the previous resolve object.

e.g. store._jobs.fetch.each ...
e.g. Promise.new.resolve([1, 2, 3]).length <= returns a promise that resolves into the
length of the array
e.g. Promise.new.resolve(4) + 3 <= returns a promise that resolves into 7

An error will be raised if the promise got rejected.

### CODE REVIEW

**Comment by pencilcheck** [comment]
Btw, this change is also a workaround on passing a block in attribute or content binding since the html parser can't handle {} in a {{}} properly yet.

e.g. <input type="text" name="name" placeholder="Name" value='{{ fetch_current_user.then {|user| user._name} }}'> will result in an error. fetch_current_user returns Volt.fetch_current_user

**Comment by ryanstout** [comment]
One thing, raising in a promise will get wrapped back up in the promise.

I'm not sure if you were in on the conversation, but I had this exact same idea.  I'm still debating it though because it makes things a little confusing.  It feels a bit like cleverness over clarity.  That said, I really don't like using promises and want a way to write synchronous API's.  What I want to do long term is write an extension to opal to support an async/await api (like C# or ES7).  The cool thing is we could make it work in MRI also with fibers.

The problem is some things don't work as you would expect.

Example:
```ruby
begin
  a = store._items.fetch_first
  a._first_name + " " + a._last_name
rescue => e
  ..
end
```

This won't work for a few reasons: 1) your adding a string to a promise, and then 2) any errors won't be captured.  Doing a parser extension and async/await would make this all work as expected.

Also, I think if people don't understand when they are working with a promise, you might get more issues than its worth.

I am interested in trying the method_missing approach though, but I kind of want to see how it works for people.  Would you be interested in moving it to a gem?

**Comment by pencilcheck** [comment]
Sure, that is fine with me.

**Comment by ryanstout** [comment]
@pencilcheck cool.  I think if people like it and aren't confused by it, then I'll pull it into volt.  I just want to work out the kinks first and make sure its not too confusing.

**Comment by pencilcheck** [comment]
https://rubygems.org/gems/opal-promise-patch

**Pull request closed without merging**
