### PR TITLE
Small code improvement.

### PR DESCRIPTION
**Pull request by gfvcastro**

### CODE REVIEW

**Comment by ryanstout** [comment]
I'm not sure if these have been updated, but they are still incorrect.

**Comment by ryanstout** [comment]
On master this causes the test to fail, if you have time, please update and resubmit.  I think maybe you have a flipped boolean in there.  Thanks!

**Comment by ryanstout** [comment]
reopened.  Thanks

**Comment by gentoid** [comment]
@gfvcastro small hint: if you change commits with ```git rebase -i``` and ```git push -f``` in your repo (I'd prefer to squash all the commits into one) then this PR automatically will contain clean history

**Comment by ryanstout** [comment]
merged, thanks!

**Pull request merged**
