### PR TITLE
fix array.last for empty array

### LINKED ISSUE #258: array model last broken
page._issues!
page._issues.last
IndexError: index -1 too small for array; minimum: 0

I can fix that when i have some time

### PR DESCRIPTION
**Pull request by dancinglightning**
fixes #258

### CODE REVIEW

**Comment by dancinglightning** [comment]
hmm, while i'd like to say great, i admit to feeling a bit put out. 
Since your code now does the same test as my pull request, and contains the same fix (return nil) 
i have troubles seeing why you didn't accept it. 
I saw that you had extra tests and code, but that could just as easily have been put in after.
Slightly demotivating is all i'm saying, i mean if this is how is goes with tiny things . . ..

**Comment by ryanstout** [comment]
@dancinglightning sorry, I had already started changing things before I noticed you had the PR.  (just missed it on github somehow).  Also, I ended up noticing that there was another issue with size changes when using last, so I switched it to calling .size (which depends on @size_dep, and fixes that issue).  At first I thought the issue was because of the size dep problem.  Again, sorry.  I wasn't trying to keep you from getting the credit or anything :-)

**Comment by dancinglightning** [comment]
ok, i understand if you had started already
thanks for explaining,
i guess i was just sensitive as it was my first pr

**Comment by ryanstout** [comment]
@dancinglightning sorry, I know how that goes.  I'll be more careful next time.

**Pull request closed without merging**
