### PR TITLE
rename notices.css.scss to notices.scss

### PR DESCRIPTION
**Pull request by neurodynamic**
I found an error on deployment via Intercity is fixed by this change, which is the convention now, anyway, I believe?

### CODE REVIEW

**Comment by ryanstout** [comment]
@neurodynamic any docs on this being the convention now.  Volt uses sprockets for this part, which I thought always used the .css.scss ext.  Thanks!

**Comment by neurodynamic** [comment]
Here it is: [link](https://github.com/rails/sprockets/blob/09a7f56fe403700301467d3b14ee08e3aa713643/UPGRADING.md#prefer-just-foocoffee-and-fooscss)

**Comment by ryanstout** [comment]
@neurodynamic until I (or someone else) can get some time we're still on sprockets 2.0 because we're still on opal 0.7. I started upgrading a while ago, but it's going to be more complicated than just changing some gem versions. I've been really busy this week, but hopefully will have time to work on the upgrade soon.

**Comment by ryanstout** [comment]
Merged now that we're on sprockets 3.  Thanks!

**Pull request merged**
