### PR TITLE
rename to current user and cleanup

### PR DESCRIPTION
**Pull request by dennym**
Changes in component user-templates will be necessary when upgrading the component to the latest volt version.

### CODE REVIEW

**Comment by ryanstout** [comment]
@dennym What's your reason for wanting to change user to current_user?

**Comment by dennym** [comment]
Just a naming convention thing. If returns the current user so the method should be named current_user. If I think of method name `user` without knowing what it does, its hard to guess that it returns the current user.

 The same for  `def user?`. Without knowing how it works I would think it checks for the class and returns true or false for the given object. Todo.user? #=> false.

Hope I could explain it well enough.

**Comment by ryanstout** [comment]
@dennym I feel like either way your not just going to guess "Volt.user" or "Volt.current_user", your going to have to look at the docs.  For me it's something your going to call a lot and having the shorter name will be nice.  Rails is really the only framework (that I know of) that uses the current_user convention.  Let me ask people's thoughts on gitter.

**Comment by dennym** [comment]
https://github.com/voltrb/volt-user-templates/pull/4 for completion

**Comment by ryanstout** [comment]
just an update, I'm going to do this before the next gem release, since I need to update a bunch of repo's and docs.  Hopefully soon.

**Comment by ryanstout** [comment]
Sorry, I didn't end up merging this.  A lot had changed, so I just redid it.  Its in master now, should go out soon.

**Pull request closed without merging**
