### PR TITLE
Validator cleanup

### PR DESCRIPTION
**Pull request by lexun**
Just finishing up the refactor from a while ago when I made the format validator class. This removes the need to override new on the email and phone number validators by making format validator their superclass. It also drys up the specs by extracting common ones to shared examples.

### CODE REVIEW

**Comment by lexun** [comment]
Hey @ryanstout, any idea why the build keeps failing for only ruby 2.1.1 ?

https://travis-ci.org/voltrb/volt/builds/50291411
https://travis-ci.org/voltrb/volt/builds/50290961

Something about ` cannot load such file -- volt/bootstrap/version `
Could it be a dependency caching thing?

**Comment by danielpclark** [comment]
Where is the require actually pointing?
https://github.com/voltrb/volt-bootstrap/blob/master/lib/volt/bootstrap.rb#L1

The travis path of the require /home/travis/build/voltrb/volt/vendor/bundle/ruby/2.1.0/gems/volt-bootstrap-0.0.8/lib/volt/bootstrap.rb:1:in has 'volt/bootstrap/version' for the require path but there is no 'bootstrap' folder or 'version.rb' file in it.  There is a VERSION file in the root directory, but it doesn't look like that fits the require path to me.

Another way you could ask the same question is "why is it even passing in all the other versions?"

**Comment by ryanstout** [comment]
@lexun thanks for working on this.  I fixed the travis issues.  (Combination of a few things)  Pulling this in in a few.

**Comment by ryanstout** [comment]
@lexun merged, Thanks!

**Comment by ryanstout** [comment]
fyi, I'm getting pretty close to having a few big features of mine out.  Once thats done I'm going to test all of the demo apps/component gems and do a gem release.

**Pull request merged**
