### PR TITLE
Use __dir__ where appropriate

### PR DESCRIPTION
**Pull request by bbatsov**
I've also removed a few redundant usages of `File.join`.

### CODE REVIEW

**Comment by dfyx** [comment]
`__dir__` is not defined in opal.

**Comment by bbatsov** [comment]
Guess this is something we can easily fix. 

Unfortunately for some reason the tests aren't working locally for me. They just hang:

```
Run specs in Opal
--------------------------
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:9999, CTRL+C to stop
TypeError: undefined is not an object (evaluating 'args[0]')

  /Users/bozhidar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/opal-rspec-0.4.0/vendor/spec_runner.js:17 in global code
```

**Comment by ryanstout** [comment]
how did I not know about __dir__ ?  (And why isn't it __DIR__)  I'll pull this down locally and see if it works.

**Comment by ryanstout** [comment]
Ok, yea, no __dir__ support in opal.  The requires are done as a preprocessing step in opal.  Feel free to submit a PR or issue on them and when they add it we can use it.

**Comment by dfyx** [comment]
> (And why isn't it DIR)

Because __dir__ is a method, not a (pseudo-)constant.

**Comment by ryanstout** [comment]
@dfyx cool, make since. :-)

**Pull request closed without merging**
