### PR TITLE
Observe hidden input and select value attr

### PR DESCRIPTION
**Pull request by pencilcheck**
Added MutationObserver to support observing hidden input attribute changes,
and also add support for select tag changes

It was not possible to observe value attr changes for hidden input since it does not trigger event by default, the same for select which requires watching on a different event. This commit fixes that.

MutationObserver is supported on all browsers except IE 10 and Opera Mini.
http://caniuse.com/#feat=mutationobserver

So this commit contains a polyfill of MutationObserver as well.

### CODE REVIEW

**Comment by ryanstout** [comment]
Can you explain the use case for observing on hidden fields?  It would be great to support that, but it's a trade off with the number of bytes we have to ship to the client and parse. Is there a smaller polyfil library?  Or maybe if the use case isn't that common it would make more since to make support in a gem?

**Comment by pencilcheck** [comment]
Semantic UI's form uses hidden fields for manipulating the fields of a dropdown. A lot of forms uses hidden fields for hidden values as well, there are definitely uses for them I don't know why I have to explain the use cases ... If we don't care about IE 10 or Opera we can remove the polyfill.

**Comment by ryanstout** [comment]
IE 10 is on the list, but not below.  I wanted to explain the use cases because I didn't know why you would need it :-)  Is there a smaller polyfill out there?  Thats a lot of code to add.

**Comment by pencilcheck** [comment]
I can't find any smaller polyfills, most of them are about the same size as the one I have but I can put it into a separate file and minimize it. Someone made a minimized version of the MutationObserver and it is only 3.4KB, even smaller when gzipped.

https://github.com/megawac/MutationObserver.js/tree/master/dist

We can use this one instead.

**Comment by ryanstout** [comment]
Cool, yea, that one looks a lot smaller.  The other one had some duplication with things we already had also (setImmediate)  You can just use the unminified version, since production has compression, and then in dev mode they can see the source.  Thanks

**Comment by ryanstout** [comment]
Actually, I'm thinking about adding an IE8-10 gem that adds support for IE8-10 if you need it.  Maybe we should start that?  Thoughts.

**Comment by pencilcheck** [comment]
http://caniuse.com/#compare=ie+10,chrome+45

I don't know, there are a lot of things ie 10 doesn't support. But it is a good idea, I like that actually.

**Comment by pencilcheck** [comment]
I wonder would that basically means including all polyfills including ES5, ES6 to the gem?

**Comment by pencilcheck** [comment]
Ah, the one implementation I found uses setTimeout for everything, probably not a good idea. Also it doesn't work on input text, so I'm reverting back to the previous implementation.

**Comment by ryanstout** [comment]
We already have a setImmediate polyfill included, fyi.

**Comment by ryanstout** [comment]
Merged, I didn't pull the very latest, so it didn't show, but I made the same changes.

**Pull request closed without merging**
