### PR TITLE
Supports class variables in attr binding

### PR DESCRIPTION
**Pull request by pencilcheck**
Combined with https://github.com/voltrb/volt/pull/190 you can do

e.g. `<input type='text' value='{{ Volt.fetch_current_user._name }}' />`

### CODE REVIEW

**Comment by ryanstout** [comment]
Class variables work in attr bindings as is, why is this needed?  Also, your example isn't using class variables.

**Comment by pencilcheck** [comment]
I have trouble naming the thing I was referring to. If it is not class variables it is more of anything starting with a capital Class. Right now in attribute_scope it only allows setting a setter with lower case letters.

**Comment by ryanstout** [comment]
Can you make a spec for this?  This will fail if you just put in a Class directly.

**Comment by pencilcheck** [comment]
That's intended, you are not allowed to just put a class in the attribute binding because it doesn't make sense to bind to a class. It checks to see if there is a "." in the expression.

**Comment by ryanstout** [comment]
Sorry, my bad, I read it wrong.  I was referring to something else.

**Pull request merged**
