### PR TITLE
Fix test suite for native ruby.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by iliabylich** [comment]
@ryanstout can you review it please?

**Comment by ryanstout** [comment]
Merging.  One question, what was the use case for adding the ```directory?``` check?  It would be good to comment why that's there.  Thanks!

**Comment by iliabylich** [comment]
@ryanstout there was a problem with opal-rspec which has a file https://github.com/opal/opal-rspec/blob/v0.3.0.beta3/app/rspec-builder.rb. this file doesn't exist in master branch anymore so I think this is a temporary workaround.
There was more interesting issue with changing method name from symbol to string. I still don't understand exactly why it happens, but for some reason method defined using symbol as its name disappears. I think it may be related to new GC in ruby 2.2 which collects symbols. Using strings as a method name fixes the issue. I had no time to check it with other versions of ruby, but I'm 100% sure that it reproduces only on 2.2.
Thanks for merging my PR!

**Comment by ryanstout** [comment]
No problem, would you want do another quick PR and add a comment about the
rspec-builder issue?  Just so we remember why that's in there?

Thanks

**Pull request merged**
